/*
 * This source file was generated by the Gradle 'init' task
 */
package io.github.softeng_g8.software_evolution;

import org.junit.jupiter.api.Test;

class AppTest {
    @Test void appHasAGreeting() {

    }
}
